version: "3"

services:
  server:
    build: app_card/
    # restart: always
    ports:
      - 80:3000
    # volumes:
    #   - ./app_card/public:/app/public
    #   - ./app_card/src:/app/src
    #   - ./app_card/styles:/app/styles
    # # command: npm run start
